### ISSUE TITLE
conda install still requires jupyterlab < 4?

### ISSUE THREAD

**Issue by ipcoder** [holoviz/pyviz_comms#115]
It seems that installing using conda downgrades to jupyterlab to 3.xx

**Comment by maximlt** [comment]
Hi @ipcoder, could you indicate from which conda channel you are installing pyviz_comms and jupyterlab? I just noticed pyviz_comms 3.0.0 was just released on `conda-forge` and not on `pyviz` or `defaults` yet.

**Comment by ipcoder** [comment]
I have tired again (my default is conda-forge) and it works now. Thanks

**Comment by ipcoder** [comment]
Seems to be resolved
