### ISSUE TITLE
output_view does not work

### ISSUE THREAD

**Issue by akhmerov** [holoviz/pyviz_comms#3]
Jupyterlab allows to create a separate view for any cell output. With `HoloMap` or `DynamicMap` outputs this fails with the following error in the js console:

```
nouislider.js:2081 Uncaught Error: noUiSlider (9.2.0): Slider was already initialized.
    at V (nouislider.js:2081)
    at Object.G [as create] (nouislider.js:2133)
    at Object.s [as init_slider] (widgets.js:79)
    at <anonymous>:85:11
    at t.attachWidget (docklayout.js:455)
    at t.addWidget (docklayout.js:353)
    at t.addWidget (dockpanel.js:303)
    at t.addToMainArea (shell.js:399)
    at Object.open (index.js:56)
    at a (manager.js:341)
    at e.addSibling (context.js:358)
    at execute (index.js:1020)
    at e.execute (index.js:350)
    at t.triggerActiveItem (menu.js:305)
    at t._evtMouseUp (menu.js:641)
    at t.handleEvent (menu.js:451)
V @ nouislider.js:2081
G @ nouislider.js:2133
s @ widgets.js:79
(anonymous) @ VM538:85
t.attachWidget @ docklayout.js:455
t.addWidget @ docklayout.js:353
t.addWidget @ dockpanel.js:303
t.addToMainArea @ shell.js:399
open @ index.js:56
a @ manager.js:341
e.addSibling @ context.js:358
execute @ index.js:1020
e.execute @ index.js:350
t.triggerActiveItem @ menu.js:305
t._evtMouseUp @ menu.js:641
t.handleEvent @ menu.js:451
```

To reproduce, run
```python
import holoviews as hv

import bokeh
import numpy as np

bokeh.__version__

hv.extension('bokeh')

frequencies = [0.5, 0.75, 1.0, 1.25]

def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

# When run live, this cell's output should match the behavior of the GIF below
dmap = hv.DynamicMap(sine_curve, kdims=['phase', 'frequency'])
dmap.redim.range(phase=(0.5,1)).redim.range(frequency=(0.5,1.25))
```
and select "create new view for output" from the right-click menu option:

![image](https://user-images.githubusercontent.com/2069677/39664618-0cd39e0c-5086-11e8-845a-e96d28cdf5e0.png)

**Comment by philippjfr** [comment]
Would definitely be great if this worked, not sure what it would take though.

**Comment by shenker** [comment]
I agree, it would be great to get this working! But this isn't just a problem for `HoloMap`s or `DynamicMap`s, it's a general issue (on holoviews/bokeh master).

In JupyterLab if I run `hv.Curve(np.random.random(10))`, then right-click and “Create New View for Output,” an empty output window opens and a second plot appears in the original notebook output cell (but nothing in the separate output window). No JS error. Repeated “Create New View”s will create arbitrarily many duplicates of the plot in the original output cell, but nothing in the separate output window.

**Comment by cocoaaa** [comment]
I've observed this behavior as well when I open a new view of the same notebook in JupyterLab (#3623). However, today I noticed that not all the output figures generate the duplicate figure (upon creating the second view of the notebook).

In the recording below, first I have two views of a notebook open, and you see that the second view doesn't show any output figures while the first notebook has duplicated output figures. So I close the notebook views and refresh the browser, and open the same notebook. At this point, the notebook has a single output figure. Then, I open a second view of this notebook and we see that the output figure is generated on the first notebook as reported by @shenker as well.  However, we see that the output figure of the `HoloMap` object (`hmap_2d`) does not have this second output figure generated unlike the `hv.Curve` object.  

<img src="https://media.giphy.com/media/d7qfqm3NLeC12rwtLu/giphy.gif" height="600" />



@philippjfr: Do you have any idea why they behave differently? And if it's possible to at least have all figures not being duplicated when the second view of the notebook is open? It'd be much better not to have the duplicated figures appear for all the outputs at least for now.  

Thanks!

**Comment by mtkilic** [comment]
Did anyone find workaround for this issue?

**Comment by hadim** [comment]
I am also facing the same issue using Panel. See https://github.com/pyviz/panel/issues/483

I pinged JLab devs on Gitter.

I am wondering if it could be related to the JS injection done when importing the library (such as `pn.exension()` or `hv.etension` for example). I guess the JS is not injected in the second view and so the view cannot display correctly the output. Does that make sense?

**Comment by philippjfr** [comment]
This almost certainly related to the fact that bokeh does not allow rendering the same model twice on the same page.

**Comment by hadim** [comment]
Indeed, when creating a new view, the previous one (the one in the notebook) still displays the output (you can do the test with a simple `print`). So if Bokeh cannot render twice the model view, then it's definitively a Bokeh issue.

**Comment by jsignell** [comment]
I am wondering if this could be resolved by not displaying the panel object in the original notebook if there is an "Output View". This is kind of a workaround  for the bokeh issue, but I suspect that it is more often what people would want anyways.

**Comment by NumesSanguis** [comment]
Encountered the same thing of double output in the Notebook, but none in the Output View. Just to add some more sample code to this issue:

## Working (normal JupyterLab widgets):
```python
from ipywidgets import interact

interact_call = interact()

@interact_call(dict_sample={"None": None, "call_1": 1, "call_2": 2})
def show_dict_values(dict_sample):
    if dict_sample:  # exclude None
        print(dict_sample)
```
## Not working (Pyviz Panel)
Create sample audio
```python
import numpy as np

# create sound
sps = 44100 # Samples per second
duration = 10 # Duration in seconds

modulator_frequency = 2.0
carrier_frequency = 120.0
modulation_index = 2.0

time = np.arange(sps*duration) / sps
modulator = np.sin(2.0 * np.pi * modulator_frequency * time) * modulation_index
carrier = np.sin(2.0 * np.pi * carrier_frequency * time)
waveform = np.sin(2. * np.pi * (carrier_frequency * time + modulator))
    
waveform_quiet = waveform * 0.3
waveform_int = np.int16(waveform_quiet * 32767)
```

Right-click cell --> Create New View for Output --> Execute cell with this code:
```python
import panel as pn
pn.extension()

audio = pn.pane.Audio(waveform_int, sample_rate=sps)
audio
```

**Expectation:** Audio widget displayed in Output View
**Reality:** Audio displayed twice in Notebook, 0 times in Output View

![JupyterLab_output-view_Panel-broken](https://user-images.githubusercontent.com/8008618/69777204-977c2c80-11e2-11ea-9de1-710a6af725f8.png)

**Comment by vhphan** [comment]
Is there a solution to this 'double output' issue?

**Comment by maximlt** [comment]
It'd be great if this issue could be fixed! It'd make developing a figure or an app in Jupyter Lab even better :)

**Comment by philippjfr** [comment]
So I was about respond to say I could see no approach to make this work. However I just played around a bit and got this mostly working. The main issue is that we can only keep one of the views synced. The second problem is that when the cell with the original view is deleted or rerun the second view also gets cleaned up. I'll keep thinking about those issue but I can now say that this is possible at least in theory and with some caveats.

**Comment by maximlt** [comment]
@philippjfr thanks for trying to address that issue! The discussion should maybe live on jupyter_bokeh?

**Comment by philippjfr** [comment]
HoloViz tools do not use jupyter_bokeh for rendering. If we figure out a solution here we can absolutely port it to bokeh though.

**Comment by mpanighel** [comment]
> I just played around a bit and got this mostly working.

Great @philippjfr ! Are you tweaking on bokeh or jupyter code?

> The main issue is that we can only keep one of the views synced.

As a starting point maybe the most obvious is to keep synced just the new view. One could even think to redirect all the output in the new view, leaving the original empy (i.e. with no output).

> The second problem is that when the cell with the original view is deleted or rerun the second view also gets cleaned up.

If it happens when the original is deleted I think it is not a big issue. If the second view is cleaned also when the original is just rerun, that is more problematic.

**Comment by mpanighel** [comment]
> This almost certainly related to the fact that bokeh does not allow rendering the same model twice on the same page.

> The main issue is that we can only keep one of the views synced.

@philippjfr Still, if it is a problem of bokeh rendering twice the same model, I do not get how now the original view shows actually two independent bokeh plots. Having no clue at all on the functioning of this, I expected it would be a matter of jupyter sending to the second view the html code relative to the second plot.

**Comment by jlstevens** [comment]
Looking at this issue, it sounds like this is a Bokeh limitation as opposed to a problem in pyviz_comms. @philippjfr Do you know if there is an issue/feature request on Bokeh for this?

**Comment by pnsvk** [comment]
Can someone from the core-dev team kindly help with some directions on this ?
Its annoying to have to scroll to the previously rendered elements, for every interaction with a widget that is rendered down-under, in a jupyterlab notebook..

Having multiple views happens to be one of the killer-features of jupyterlab..

**Comment by philippjfr** [comment]
I'm very happy to say that in #3652 I've finally added a (partial) fix for this issue. The PR now allows a second view to be created, note however that only the copy will update when there is a change. I'll have to do some more testing before release but it seems safe enough and is fairly simple.
