### ISSUE TITLE
Displaying PyViz objects in JupyterLab requires the jupyterlab_pyviz extension to be installed

### ISSUE THREAD

**Issue by dclong** [holoviz/pyviz_comms#33]
The below message prompts repeated. I've already have the extension installed. 
![image](https://user-images.githubusercontent.com/824507/55255830-c50a7380-5218-11e9-827c-93ee4d8ba4c0.png)
Below are versions of relevant libraries.
```
python:            3.67
jupyter             1.0.0
jupyter-client      5.2.4
jupyter-console     6.0.0
jupyter-core        4.4.0
jupyterhub          0.9.4
jupyterlab          0.35.4
jupyterlab-server   0.2.0
holoviews           1.11.3
pyviz-comms         0.7.2
@pyviz/jupyterlab_pyviz v0.7.1  enabled  OK
```

**Comment by philippjfr** [comment]
When filing an issue please provide the versions of all relevant libraries.

**Comment by dclong** [comment]
@philippjfr Sorry about that. I've update information of relevant libraries.

**Comment by philippjfr** [comment]
Perfect thanks. I'll have to look into it, there have been some changes recently which could affect things. They'll definitely be fixed once holoviews is released again but it **should** still be backward compatible.

**Comment by philippjfr** [comment]
I'm pretty sure this issue was addressed, please reopen if not.
