### ISSUE TITLE
Code cells disappear in JupyterLab when using jupyterlab_pyviz v1.0.1

### ISSUE THREAD

**Issue by jmontoyam** [holoviz/pyviz_comms#55]
Hi,

I get a strange behaviour when I use JupyterLab (v2.1.1) with the jupyterlab_pyviz v1.0.1 extension: some of the code cells get loss. At first I thought this was a JupyterLab issue, threfore I opened an issue in JupyterLab, you can find the detailed bug report at https://github.com/jupyterlab/jupyterlab/issues/8331. But apparently the problem is not JupyterLab, it is related with the jupyterlab_pyviz v1.0.1 extension: I solved the problem by downgrading jupyterlab_pyviz to version 1.0.0 and rebuilding JupyterLab. If you need any additional information apart from the one given in the bug report please let me know.

BTW, thank you very much guys for this amazing proyect!

**Comment by philippjfr** [comment]
Thanks for reporting this. This is very odd indeed but I've also seen this a couple of times before.

**Comment by philippjfr** [comment]
Just published v1.0.2 with a fix.

**Comment by jmontoyam** [comment]
Great!, thank you very much @philippjfr !...Just out of curiosity, what was the problem?...Was there a big change between 1.0.0 and 1.0.1?

**Comment by jasongrout** [comment]
The change is in the PR linked above: #56.

**Comment by jmontoyam** [comment]
I can confirm that the new v1.0.2 solved the problem, thank you very much for the friendly and quick response  @philippjfr and @jasongrout .

**Comment by philippjfr** [comment]
Glad that it's fixed for you as well, and thanks @jasongrout for being so responsive on the original issue.

**Comment by jmontoyam** [comment]
@philippjfr, @jasongrout can I ask you guys a question?...I would like to develop a JupyterLab extension that allows to view and explore interactively in JupyterLab big raster datasets (really big images, I need to use Datashader/Holoviews to avoid out of memory issues). In summary, I would like to use JupyterLab as a interactive raster data viewer just by double-clicking the raster dataset (and be able to use the nice tools provided by Datashader/Holoviews/Bokeh for interactive exploration). I would like this tiny project to be my first contribution to Datashader/Holoviews or JupyterLab. This extension would use both the client (for visualizing the data in JupyterLab) and the server (for manipulating the data using Datashader/Holoviews). What do you think about this idea?...Could you please give me some suggestion/advice about how would you start such project taking into account that I have never build a jupyterlab extension before and that I have a very basic knowledge of javascript (I mostly familiar with Python, C/C++)...Thank you very much!, and please excuse me for asking this question here but I do not know which would be the most appropriate channel for asking this question.
