### ISSUE TITLE
Syntax error in Google Colab Support

### ISSUE THREAD

**Issue by asodeur** [holoviz/pyviz_comms#62]
#### ALL software version info
 - pyviz_comms: 0.7.5
 - panel: 0.9.7
 - jupyter: 1.0.0

#### Description of expected behavior and the observed behavior
The following code will produce a JavaScript error in Jupyter:
```python
import panel as pn
pn.extension()
file_upload = pn.widgets.FileInput()
file_upload
```
results in:
```
Javascript error adding output!
SyntaxError: Unexpected token '?'
See your browser Javascript console for more details.
```
I believe this is due to a [typo](https://github.com/holoviz/pyviz_comms/blob/2f9afd5f02a94f9ff5d5fbf7fe137094942c2df1/pyviz_comms/__init__.py#L580) introduced in #61.

#### Stack traceback and/or browser JavaScript console output
Just for completeness. Not sure this is going to be of much help as the issue occurs in `eval(js)`, see above.
```
SyntaxError: Unexpected token '?'
    at OutputArea.append_javascript (outputarea.js:763)
    at OutputArea.append_mime_type (outputarea.js:696)
    at OutputArea.append_display_data (outputarea.js:659)
    at OutputArea.append_output (outputarea.js:346)
    at OutputArea.handle_output (outputarea.js:257)
    at output (codecell.js:395)
    at Kernel._handle_output_message (kernel.js:1197)
    at proxy (jquery.min.js:10502)
    at Kernel._handle_iopub_message (kernel.js:1224)
    at Kernel._finish_ws_message (kernel.js:1016)
```

**Comment by philippjfr** [comment]
Which browser aare you using out of interest?

**Comment by philippjfr** [comment]
Should have checked this earlier but here's the browser compatibility for the ``??`` operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

**Comment by asodeur** [comment]
Oh, I was assuming I am on the latest Chrome but auto-update seems to be blocked by the corporate firewall and I am on Chrome 78. Guess I better update asap ... Thx

**Comment by philippjfr** [comment]
Let's keep this open, we should have the discussion on what the minimum browser versions should be
