### ISSUE TITLE
Support JupyterLab 3

### ISSUE THREAD

**Issue by dclong** [holoviz/pyviz_comms#71]
#### Is your feature request related to a problem? Please describe.
JupyterLab 3 is out. It would be great if pyviz_comms can be updated to be compatible with JupyterLab 3. 

#### Describe the solution you'd like
Update pyviz_comms to be compatible with JupyterLab 3.

**Comment by philippjfr** [comment]
Yes, will try to work on it next week.

**Comment by philippjfr** [comment]
Just released `pyviz_comms` 2.0 which automatically bundles the JupyterLab extension. Simply upgrade with `pip install pyviz_comms --upgrade` or `conda install -c pyviz pyviz_comms`.

**Comment by iwansetwan** [comment]
I tried conda install -c pyviz pyviz_comms but I got this problem below

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

Do you know how to fix it?

**Comment by jbednar** [comment]
Usually in that case it's a good idea to select the parts of your current environment that you still need (which conda cannot know) and make a new environment with just those.  The message indicates that conda is having trouble finding a single environment that adds that new package but properly preserves all your older packages already installed.
